spring:
  application:
    name: Realo-Api
  datasource:
    username: ${PG_USERNAME}
    password: ${PG_PASSWORD}
    url: jdbc:postgresql://${PG_HOST}:5432/postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
    hibernate:
      ddl-auto: none
    open-in-view: false
  mvc:
    format:
      date: iso
logging:
  level:
    root: INFO
    com.realo: ${REALO_LOG_LEVEL}
    org.springframework.jdbc.core: ${JDBC_LOG_LEVEL}
  file:
    name: realo.log
    path: /
jwt:
  token:
    secret: realo
    expired: 900
  header: Authorization
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /system