spring:
  application:
    name: Realo-Api
  datasource:
    username: postgres
    password: pass
    url: jdbc:postgresql://host.docker.internal:5434/realo
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
    hibernate:
      ddl-auto: none
    open-in-view: false
  mvc:
    format:
      date: iso
logging:
  level:
    root: INFO
    org.springframework.jdbc.core: DEBUG
  file:
    name: realo.log
    path: /
jwt:
  token:
    secret: realo
    expired: 900
  header: Authorization
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /system