-- liquibase formatted sql

-- changeset abialiauski:1
CREATE TABLE IF NOT EXISTS revision
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    timestamp BIGINT,
    CONSTRAINT pk_revision PRIMARY KEY (id)
);

-- changeset abialiauski:2
CREATE TABLE IF NOT EXISTS estate_storage.provider_aud
(
    id            BIGINT NOT NULL,
    rev           BIGINT NOT NULL
        CONSTRAINT fkq0gu8xn27gpbday2tuhtbs9an
            REFERENCES public.revision,
    revtype       SMALLINT,
    name          VARCHAR(64),
    web_site_link VARCHAR(256),
    CONSTRAINT provider_aud_pkey
        PRIMARY KEY (id, rev)
);

-- changeset abialiauski:3
CREATE TABLE IF NOT EXISTS estate_storage.estate_aud
(
    id                    BIGINT NOT NULL,
    rev                   BIGINT NOT NULL
        CONSTRAINT fkdtlg89deuvfknplpchsj9y23u
            REFERENCES public.revision,
    revtype               SMALLINT,
    city                  VARCHAR(32),
    closest_metro_station VARCHAR(128),
    country               VARCHAR(32),
    district              VARCHAR(64),
    street                VARCHAR(64),
    description           VARCHAR(512),
    estate_type           VARCHAR(48),
    square                DOUBLE PRECISION,
    year_of_construction  INT,
    provider_id           BIGINT,
    CONSTRAINT estate_aud_pkey
        PRIMARY KEY (id, rev)
);

-- changeset abialiauski:4
CREATE TABLE IF NOT EXISTS user_storage.user_account_aud
(
    id                  BIGINT NOT NULL,
    rev                 BIGINT NOT NULL
        CONSTRAINT fkfi9ywuk505xl9g17jib6b7urx
            REFERENCES public.revision,
    revtype             SMALLINT,
    phone_number        VARCHAR(16),
    preferred_messenger VARCHAR(10),
    email               VARCHAR(128),
    first_name          VARCHAR(64),
    gender              VARCHAR(16),
    last_name           VARCHAR(64),
    login               VARCHAR(64),
    password            VARCHAR(128),
    role                VARCHAR(64),
    city                VARCHAR(48),
    country             VARCHAR(32),
    CONSTRAINT user_account_aud_pkey
        PRIMARY KEY (id, rev)
);

-- changeset abialiauski:5
CREATE TABLE IF NOT EXISTS announcement_storage.announcement_aud
(
    id                BIGINT NOT NULL,
    rev               BIGINT NOT NULL
        CONSTRAINT fk8aphoxa6nrns1mupw48r0rk9w
            REFERENCES public.revision,
    revtype           SMALLINT,
    announcement_type VARCHAR(64),
    created_at        DATE,
    details           VARCHAR(512),
    currency_type     VARCHAR(3),
    is_loan_possible  BOOLEAN,
    price             NUMERIC(19, 2),
    title             VARCHAR(64),
    user_id           BIGINT,
    estate_id         BIGINT,
    CONSTRAINT announcement_aud_pkey
        PRIMARY KEY (id, rev)
);