apiVersion: apps/v1
kind: Deployment
metadata:
  name: realo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: realo
  template:
    metadata:
      labels:
        app: realo
    spec:
      containers:
        - name: realo
          image: abialiauski/realo
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: REALO_LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: realo-configmap
                  key: REALO_LOG_LEVEL
            - name: JDBC_LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: realo-configmap
                  key: JDBC_LOG_LEVEL
            - name: PG_USERNAME
              valueFrom:
                secretKeyRef:
                  name: pg-secrets
                  key: POSTGRES_USER
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-secrets
                  key: POSTGRES_PASSWORD
            - name: PG_HOST
              value: postgres