apiVersion: apps/v1
kind: Deployment
metadata:
  name: realo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: realo
  template:
    metadata:
      labels:
        app: realo
    spec:
      containers:
        - name: realo
          image: abialiauski/realo
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: REALO_LOG_LEVEL
              value: DEBUG
            - name: JDBC_LOG_LEVEL
              value: DEBUG
            - name: PG_USERNAME
              value: user
            - name: PG_PASSWORD
              value: password
            - name: PG_HOST
              value: postgres