name: codecov
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  codecov:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11
      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-
      - run: |
          export REALO_LOG_LEVEL=DEBUG
          export JDBC_LOG_LEVEL=DEBUG
          mvn clean install
      - uses: codecov/codecov-action@v3
        with:
          files: ./target/site/jacoco/jacoco.xml
          fail_ci_if_error: true