name: Java Maven Docker CI/CD
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: | 
          export REALO_LOG_LEVEL=DEBUG
          export JDBC_LOG_LEVEL=DEBUG
          mvn clean install
      - name: Build and Push to Docker Hub
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: abialiauski/realo
          tags: 0.0.$GITHUB_RUN_NUMBER, latest
          dockerfile: Dockerfile
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}